etcd:
  - etcd:2279
  - etcd:2379
  - etcd:2479
  - etcd:2579
protocol:
  - "tcp"
  - "ws"
  - "http"
listen_ip: "0.0.0.0"
tcp_port: "9901"
http_port: "9902"
grpc_addr: ":8282"
grpc_host: voip
host: 10.0.0.218
